/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as AuthResetPasswordImport } from './routes/_auth/reset-password'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as AppUserImport } from './routes/_app/_user'
import { Route as AppAdminImport } from './routes/_app/_admin'
import { Route as AppUserIndexImport } from './routes/_app/_user/index'
import { Route as AppAdminDashboardImport } from './routes/_app/_admin/dashboard'
import { Route as AppAdminUserIndexImport } from './routes/_app/_admin/user/index'
import { Route as AppAdminUserCreateImport } from './routes/_app/_admin/user/create'
import { Route as AppAdminUserIdImport } from './routes/_app/_admin/user/$id'
import { Route as AppAdminUserEditIdImport } from './routes/_app/_admin/user/edit.$id'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const AppUserRoute = AppUserImport.update({
  id: '/_user',
  getParentRoute: () => AppRoute,
} as any)

const AppAdminRoute = AppAdminImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)

const AppUserIndexRoute = AppUserIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUserRoute,
} as any)

const AppAdminDashboardRoute = AppAdminDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminUserIndexRoute = AppAdminUserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminUserCreateRoute = AppAdminUserCreateImport.update({
  id: '/user/create',
  path: '/user/create',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminUserIdRoute = AppAdminUserIdImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminUserEditIdRoute = AppAdminUserEditIdImport.update({
  id: '/user/edit/$id',
  path: '/user/edit/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAdminImport
      parentRoute: typeof AppImport
    }
    '/_app/_user': {
      id: '/_app/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppUserImport
      parentRoute: typeof AppImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_app/_admin/dashboard': {
      id: '/_app/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAdminDashboardImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/_user/': {
      id: '/_app/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppUserIndexImport
      parentRoute: typeof AppUserImport
    }
    '/_app/_admin/user/$id': {
      id: '/_app/_admin/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof AppAdminUserIdImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/_admin/user/create': {
      id: '/_app/_admin/user/create'
      path: '/user/create'
      fullPath: '/user/create'
      preLoaderRoute: typeof AppAdminUserCreateImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/_admin/user/': {
      id: '/_app/_admin/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppAdminUserIndexImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/_admin/user/edit/$id': {
      id: '/_app/_admin/user/edit/$id'
      path: '/user/edit/$id'
      fullPath: '/user/edit/$id'
      preLoaderRoute: typeof AppAdminUserEditIdImport
      parentRoute: typeof AppAdminImport
    }
  }
}

// Create and export the route tree

interface AppAdminRouteChildren {
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminUserIdRoute: typeof AppAdminUserIdRoute
  AppAdminUserCreateRoute: typeof AppAdminUserCreateRoute
  AppAdminUserIndexRoute: typeof AppAdminUserIndexRoute
  AppAdminUserEditIdRoute: typeof AppAdminUserEditIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminUserIdRoute: AppAdminUserIdRoute,
  AppAdminUserCreateRoute: AppAdminUserCreateRoute,
  AppAdminUserIndexRoute: AppAdminUserIndexRoute,
  AppAdminUserEditIdRoute: AppAdminUserEditIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppUserRouteChildren {
  AppUserIndexRoute: typeof AppUserIndexRoute
}

const AppUserRouteChildren: AppUserRouteChildren = {
  AppUserIndexRoute: AppUserIndexRoute,
}

const AppUserRouteWithChildren =
  AppUserRoute._addFileChildren(AppUserRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppUserRoute: typeof AppUserRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppUserRoute: AppUserRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppUserRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dashboard': typeof AppAdminDashboardRoute
  '/': typeof AppUserIndexRoute
  '/user/$id': typeof AppAdminUserIdRoute
  '/user/create': typeof AppAdminUserCreateRoute
  '/user': typeof AppAdminUserIndexRoute
  '/user/edit/$id': typeof AppAdminUserEditIdRoute
}

export interface FileRoutesByTo {
  '': typeof AppAdminRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dashboard': typeof AppAdminDashboardRoute
  '/': typeof AppUserIndexRoute
  '/user/$id': typeof AppAdminUserIdRoute
  '/user/create': typeof AppAdminUserCreateRoute
  '/user': typeof AppAdminUserIndexRoute
  '/user/edit/$id': typeof AppAdminUserEditIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/_user': typeof AppUserRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/_admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/_user/': typeof AppUserIndexRoute
  '/_app/_admin/user/$id': typeof AppAdminUserIdRoute
  '/_app/_admin/user/create': typeof AppAdminUserCreateRoute
  '/_app/_admin/user/': typeof AppAdminUserIndexRoute
  '/_app/_admin/user/edit/$id': typeof AppAdminUserEditIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/'
    | '/user/$id'
    | '/user/create'
    | '/user'
    | '/user/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/'
    | '/user/$id'
    | '/user/create'
    | '/user'
    | '/user/edit/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/_admin'
    | '/_app/_user'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_app/_admin/dashboard'
    | '/_app/_user/'
    | '/_app/_admin/user/$id'
    | '/_app/_admin/user/create'
    | '/_app/_admin/user/'
    | '/_app/_admin/user/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_auth"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_admin",
        "/_app/_user"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/forgot-password",
        "/_auth/login",
        "/_auth/reset-password"
      ]
    },
    "/_app/_admin": {
      "filePath": "_app/_admin.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_admin/dashboard",
        "/_app/_admin/user/$id",
        "/_app/_admin/user/create",
        "/_app/_admin/user/",
        "/_app/_admin/user/edit/$id"
      ]
    },
    "/_app/_user": {
      "filePath": "_app/_user.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_user/"
      ]
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/reset-password": {
      "filePath": "_auth/reset-password.tsx",
      "parent": "/_auth"
    },
    "/_app/_admin/dashboard": {
      "filePath": "_app/_admin/dashboard.tsx",
      "parent": "/_app/_admin"
    },
    "/_app/_user/": {
      "filePath": "_app/_user/index.tsx",
      "parent": "/_app/_user"
    },
    "/_app/_admin/user/$id": {
      "filePath": "_app/_admin/user/$id.tsx",
      "parent": "/_app/_admin"
    },
    "/_app/_admin/user/create": {
      "filePath": "_app/_admin/user/create.tsx",
      "parent": "/_app/_admin"
    },
    "/_app/_admin/user/": {
      "filePath": "_app/_admin/user/index.tsx",
      "parent": "/_app/_admin"
    },
    "/_app/_admin/user/edit/$id": {
      "filePath": "_app/_admin/user/edit.$id.tsx",
      "parent": "/_app/_admin"
    }
  }
}
ROUTE_MANIFEST_END */
